# Generated by Django 4.2.4 on 2023-11-09 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('couverture', models.ImageField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('contenu', models.TextField()),
                ('publier', models.BooleanField(default=False)),
                ('image_couverture', models.ImageField(null=True, upload_to='media')),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('auteur', models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ManyToManyField(to='blog.article_category')),
            ],
        ),
    ]
