# Generated by Django 4.2.4 on 2023-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_couverture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
