# Generated by Django 4.2.4 on 2023-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_naissance_alter_user_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photos',
            field=models.ImageField(null=True, upload_to='media/accounts'),
        ),
    ]
